name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.32.0'
#      - name: Install dependencies
#        run: go get .
#      - name: Build Cli
#        run: make gbonsai_cli
      - name: Build WASM
        run: make gbonsai_out                
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: wasm
          path: ./build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          artifact_name: wasm

